// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.startupExperimentPrefs.browser.search.param.google_channel_row", "trow2");
user_pref("app.normandy.startupExperimentPrefs.browser.search.param.google_channel_us", "tus2");
user_pref("app.normandy.startupExperimentPrefs.privacy.annotate_channels.strict_list.enabled", true);
user_pref("app.normandy.startupExperimentPrefs.urlclassifier.trackingAnnotationTable.testEntries", "etp-experiment-1.dummytracker.org");
user_pref("app.normandy.user_id", "cd656016-595d-42c1-982e-30a1a4108834");
user_pref("app.update.auto.migrated", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1601290304);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1601290278);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1601290277);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 6779);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1601290274);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{ecdef05b-964d-4b90-bcd1-f8c5553b10f3}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1601290303112");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1601292088112");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1601290278010");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1601293878010");
user_pref("browser.search.region", "PL");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 7086);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200917005511");
user_pref("browser.startup.homepage_override.mstone", "81.0");
user_pref("browser.startup.lastColdStartupCheck", 1601290276);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\",\"cors-everywhere_spenibus-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"cors-everywhere_spenibus-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1601290277002");
user_pref("distribution.iniFile.exists.appversion", "81.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "8c7facbfb70f495aa61fc568ee1e264d");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "81.0");
user_pref("extensions.lastPlatformVersion", "81.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.cors-everywhere@spenibus", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"4f1c42e2-d8c1-4427-8644-7adc3b47a682\",\"formautofill@mozilla.org\":\"729efae7-6532-4f4a-9fd1-86dfd64a52e8\",\"screenshots@mozilla.org\":\"bacfb7cc-353b-44a3-a562-0d6234b79ee4\",\"webcompat-reporter@mozilla.org\":\"c3ec26a8-195c-4a7c-9f0a-c6a73dca8fc9\",\"webcompat@mozilla.org\":\"318e3469-35f4-40fa-851b-965bb19b37d6\",\"default-theme@mozilla.org\":\"43ca916d-a1be-4a49-ad95-5ccc3546aab6\",\"google@search.mozilla.org\":\"19f88b7b-11dc-4c1e-91de-4657d2d35717\",\"wolnelektury-pl@search.mozilla.org\":\"b1ac9763-9a1e-4ca3-b4bc-daa9b8e20911\",\"pwn-pl@search.mozilla.org\":\"2020f962-2e41-4eab-a877-85ee29381abf\",\"wikipedia@search.mozilla.org\":\"6a4ecc32-cd73-479b-bf5d-1b9605d436f9\",\"ddg@search.mozilla.org\":\"5906eedd-c59d-4563-b0e3-81ba9c878c95\",\"allegro-pl@search.mozilla.org\":\"bbb1eded-854b-48f2-bbd0-100b20a5a1f6\",\"cors-everywhere@spenibus\":\"32d25223-9851-422a-b4a8-b5cd3704f623\"}");
user_pref("gfx-shader-check.build-version", "20200917005511");
user_pref("gfx-shader-check.device-id", "0x5917");
user_pref("gfx-shader-check.driver-version", "27.20.100.7990");
user_pref("gfx.crash-guard.status.wmfvpxvideo", 2);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "81.0");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x5917");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "27.20.100.7990");
user_pref("layers.mlgpu.sanity-test-failed", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.advanced-layers", true);
user_pref("sanity-test.device-id", "0x5917");
user_pref("sanity-test.driver-version", "27.20.100.7990");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20200917005511");
user_pref("sanity-test.webrender.force-disabled", false);
user_pref("security.sandbox.content.tempDirSuffix", "{e158d80c-0572-46bb-8b3c-d5471511d749}");
user_pref("security.sandbox.plugin.tempDirSuffix", "{a5e58ec4-0df2-46bc-b287-ac52c884797c}");
user_pref("signon.usage.hasEntry", false);
user_pref("toolkit.startup.last_success", 1601290268);
user_pref("toolkit.telemetry.cachedClientID", "cebb1b77-e1d1-4555-b3cf-70a760ed31f7");
user_pref("toolkit.telemetry.previousBuildID", "20200917005511");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
